### ISSUE TITLE
Reading Universal Derivations v1.1 with the API fails due to cyclic relations

### ISSUE THREAD

**Issue by ColemanHaley** [vidraj/derinet#22]
For example, with the czech derinet from Universal Derivations:

UDer-1.1/cs-DeriNet/UDer-1.1-cs-DeriNet.tsv

I import derinet.lexicon from  tools/data-api/derinet2 directory
```
import derinet.lexicon as dlex
lexicon = dlex.Lexicon()
lexicon.load("UDer-1.1/cs-DeriNet/UDer-1.1-cs-DeriNet.tsv")
```

after processing the file for a while, the following error occurs:
```
Traceback (most recent call last):
  File "/home/hpchale2/research/infder/derinet/tools/data-api/derinet2/derinet/lexicon.py", line 102, in load
    switch[fmt](data_source, on_err)
  File "/home/hpchale2/research/infder/derinet/tools/data-api/derinet2/derinet/lexicon.py", line 414, in _load_derinet_v2
    self.add_univerbisation(parents, parent_lexeme, lexeme, feats=feats)
  File "/home/hpchale2/research/infder/derinet/tools/data-api/derinet2/derinet/lexicon.py", line 880, in add_univerbisation
    rel.add_to_lexemes()
  File "/home/hpchale2/research/infder/derinet/tools/data-api/derinet2/derinet/relation.py", line 81, in add_to_lexemes
    raise DerinetCycleCreationError("Cyclic relation detected between {} and {}".format(self.main_source, lexeme_to_check))
derinet.utils.DerinetCycleCreationError: Cyclic relation detected between karta#NNF??-----A---? and grafika#NNF??-----A---?

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/hpchale2/research/infder/derinet/tools/data-api/derinet2/derinet/lexicon.py", line 106, in load
    raise DerinetFileParseError("An error happened while parsing input file.") from exc
derinet.utils.DerinetFileParseError: An error happened while parsing input file.
```

I get similar errors for some other derivational networks, however some do not yield an error. For example  EtymWordNet-por  works.

**Comment by vidraj** [comment]
Hello,

first of all, thank you for the report!

This is a known error in DeriNet 2.1. We intend to release a new version in the coming weeks / few months, but I can't give any promises. I'm surprised you're hitting similar issues in other Universal Derivations resources, though. Can you, please, provide a full list of the problematic files?

In the meantime, the recommended workaround is to use the `on_err` parameter of [`Lexicon.load()`](https://github.com/vidraj/derinet/blob/c600da1235dce80d754bd988e0a7923c1d6da981/tools/data-api/derinet2/derinet/lexicon.py#L72) as follows:
```python3
lexicon.load("UDer-1.1/cs-DeriNet/UDer-1.1-cs-DeriNet.tsv", on_err="continue")
```

A slight issue is that this may skip other errors than just cyclic relations. DeriNet should be otherwise clean, but that might not be true for the other broken resources.

**Comment by vidraj** [comment]
> I'm surprised you're hitting similar issues in other Universal Derivations resources, though. Can you, please, provide a full list of the problematic files?

I just tried loading all UDer 1.1 resources and no errors were reported. If you are able to reproduce the issue, please paste the full logs here.

**Comment by ColemanHaley** [comment]
Hi, thanks for the tip about the on_err param! After double checking, was not able to reproduce for anything other than czech. Closing the issue, thanks for your help.

**Comment by vidraj** [comment]
No problem. If you have any other questions, feel free to ask.
